events {}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80;

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    location /two-ships/ {
      proxy_pass http://two-ships:80/;
    }

    location /space-word/ {
      proxy_pass http://space-word:80/;
    }
  }
}