name: Space Word CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  ci-space-word: # intégration continue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # On installe Cypress à la racine et http-server dans le dossier du jeu pour pouvoir lancer le serveur de test
        run: |
          npm install
          cd games/space-word && npm install

      - name: Lint
        run: cd games/space-word && npx eslint script.js

      - name: Unit tests
        run: cd games/space-word && npm test

      - name: Cypress Functional Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start --prefix games/space-word
          wait-on: 'http://localhost:3000'
          spec: cypress/e2e/space-word.cy.js

      - name: Security audit
        run: cd games/space-word && npm audit --audit-level=critical

  cd-space-word: # déploiement continu
    runs-on: ubuntu-latest
    needs: ci-space-word # attend que le CI passe avant de déployer

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./games/space-word
          destination_dir: space-word # déploie dans un sous-dossier